[build]
  command = "npm run build" # Replace this with your build command if needed
  functions = "netlify/functions" # Adjust the path to your functions folder if necessary

[scheduled_builds]
  functions = [
    { name = "scheduledFunction", cron = "*/2 * * * *" }
  ]
